version: '3.2'

services:
  frontend:
    container_name: albion_black_market_flipper
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "unless-stopped"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.albion_black_market_flipper.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.albion_black_market_flipper.entrypoints=websecure
      - traefik.http.routers.albion_black_market_flipper.tls=true
      - traefik.http.routers.albion_black_market_flipper.tls.certresolver=le

networks:
  proxy:
    external: true
